### ISSUE TITLE
automatische Gruppeninitialisierung mit Spielernamen

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/Adler_Base_18.Altis#1]
Neue Spieler automatisch im dynamische-Gruppen-System anmelden. Gruppe nach Namen des Spielers benennen.

--> Positionen anderer Spieler können über das BluForceTracking gefunden werden

***

initPlayerLocal.sqf:
```sqf
[] spawn {
    waitUntil {!isNull player};
    ["RegisterGroup",[group player,player,[nil,name player,false]]] remoteExec ["BIS_fnc_dynamicGroups",2,false];
};
```

**Comment by AdlerXiviD** [comment]
Fixed
