### ISSUE TITLE
Request: Teleporter vom Fahrzeugspawner zum Flugzeugspawnpunkt

### ISSUE THREAD

**Issue by Eras308** [gruppe-adler/Adler_Base_18.Altis#11]
Ein Teleporter vom **Fahrzeugspawner** zum **Flugzeugspawnpunkt** würde es Piloten erleichten zu den Flugzeugen zukommen,

**Comment by AdlerXiviD** [comment]
Die Funktion "Mount" ermöglicht genau das. Auf das Fahrzeug klicken und "Mount" auswählen.

**Comment by Eras308** [comment]
Ahh, ok nicht gesehen!
