### ISSUE TITLE
Kein Insta respawn

### ISSUE THREAD

**Issue by Eras308** [gruppe-adler/Adler_Base_18.Altis#12]
Ich würde mir wünschen, dass Insta respawn ausgestellt wird. Der Respawn über das Esc Menü ist nur zwei Klicks entfernt und deshalb völlig ausreichend! Wenn das normale Medic System greifen würde könnte man auch eine schnelle Mission per Zeus hier spielen ohne selber was zu bauen! Ich fänds gut! Was denkt ihr? :)

**Comment by AdlerSalbei** [comment]
Eingebaut
