### ISSUE TITLE
Funkfrequenzen vorkonfigurieren

### ISSUE THREAD

**Issue by Synch2k** [gruppe-adler/Adler_Base_18.Altis#13]
Vorkonfigurierung der Funkgeräte, damit Spieler in der Base kommunizieren zu können, ohne nebeneinanderzustehen oder vorher Funkfrequenzen zu erraten / selbst festzulegen

**Comment by Fusselwurm** [comment]
*plz note:*
* in <TFAR-1.0.268 this is done via module settings or global variable, and is known to be buggy (i.e. some players will still get random frequencies)
* in >=TFAR-1.0.268 this is done via CBA settings, and claimed to be reliable:tm:

**Comment by AdlerXiviD** [comment]
TFAR - Standardkanäle via Modul auf 50, 60, 70 eingestellt.
