### ISSUE TITLE
Infotafel Status Airborne

### ISSUE THREAD

**Issue by SlantX** [gruppe-adler/Adler_Base_18.Altis#15]
Der Status wird nicht entfernt, wenn ich lande.

Bin mit dem Apache bissel rumgeflogen, hab das Heligame gespielt und danach gelandet und den Heli per Vehicle-Spawner gelöscht. Trotzdem wird noch Airborne angezeigt.

**Comment by AdlerXiviD** [comment]
Kann ich bestätigen, ist mir auch schon passiert.

**Comment by simmax100** [comment]
airborn ist etwas unglücklich ausgedrückt.
Angezeigt wird eigentlich wenn man in einem Luftfahrzeug sitzt.
McDiod hat da den Codeblock dazu geschrieben. Keine Ahnung was da gemacht wird.

**Comment by nomisum** [comment]
Die Anzeige basiert auf einem GetOut Eventhandler. Wenn man also nicht korrekt aussteigt, rafft das die Anzeige nicht. Müsste man also am Besten nich darauf horchen ob das Fahrzeug noch existiert/lebt.

**Comment by SlantX** [comment]
Ich habe nicht im Apache gehockt. Bin ausgestiegen, zum VehicleSpawner gelaufen und habe dort den Apache gelöscht. Danach war immer noch das Airborne Lämpchen an.

**Comment by McDiod** [comment]
Hm, wenn du normal ausgestiegen bist sollte der GetOut Eventhandler ja eigentlich gefeuert haben. Ich gucks mir an.

**Comment by McDiod** [comment]
Durch normales ein-/aussteigen hab ichs nicht reproduzieren können. Wenn man abstürzt tritt der Fehler aber auf. Könnte mit ba0c4c0c4ec48edda87eba108b6e74124f78e275 gefixt sein.

**Comment by SlantX** [comment]
Wenn man stirbt und respawned geht immer noch der Marker nicht aus.
