### ISSUE TITLE
Flaggen Outdoor Shooting Range wehen nicht im Wind

### ISSUE THREAD

**Issue by SlantX** [gruppe-adler/Adler_Base_18.Altis#16]
Was im Titel steht. :)

**Comment by simmax100** [comment]
Sind aus Beton die Teile.
Ich sehe es mir mal an. Ist mir auch schon aufgefallen

**Comment by simmax100** [comment]
Keine Ahnung warum die bei uns auf dem server nicht gehen. Vermute irgendeine ACE Einstellung die da da Ärger macht. Im SP geht es

**Comment by nomisum** [comment]
könntest du evtl auf deinem server mal gegentesten @simmax? das wäre der beweis für ein serverspezifisches problem (könnte ja auch ein generelles problem mit dedicated momentan sein)

**Comment by nomisum** [comment]
im lokalen MP waren sie bei mir nach kurzer bewegung auch eingefroren.

wind von 10 auf 100 stellen in den environment settings hat geholfen.

mission mit 100 wind ist als adler_base_2017_nomiWindTest.altis auf dem server und funktioniert dort auch.
