### ISSUE TITLE
Vehicle Spawner im Meer

### ISSUE THREAD

**Issue by Eras308** [gruppe-adler/Adler_Base_18.Altis#17]
IST: 
Wenn man im Vehicle Spawner ein Fahrzeug spawnt und auf den Button klickt, dann geht die Kamera des Spawners ins Meer.

SOLL:
Die Kamera sollte nach dem spawnen auf dem Fahrzeug spawnen.

**Comment by AdlerXiviD** [comment]
Workaround: Einfach die Kamera bewegen, dann funktioniert es.

**Comment by Eras308** [comment]
Trotzdem ein Bug. :-D

**Comment by McDiod** [comment]
fixed af50cd7a2fbff1241801f55617203d4eb7eb5d13
