### ISSUE TITLE
ACE Nightvision standardmäßig auf ein spielbares Niveau stellen

### ISSUE THREAD

**Issue by Eras308** [gruppe-adler/Adler_Base_18.Altis#18]
Ich würde mir wünschen, dass die ACE Nightvision Einstellung standardmäßig auf ein spielbares Niveau gestellt werden. Bei Fragen, einfach fragen. Soll heißen am liebsten so wie es vor dem Update war, aber auf jeden Fall besser als mit bloßen Augen (ohne NVG).

Eras

**Comment by nomisum** [comment]
Sind jetzt serverseitig auf 0 und müssen in der Mission angepasst werden.

0, 0.7, 0.4 als Richtwerte
