### ISSUE TITLE
Tippfehler im Ladebildschirm

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/Adler_Base_18.Altis#2]
Danke auch an alle**N** Mitwirkenden

**Comment by chris579** [comment]
Grammatisch ist der Satz durchaus korrekt. Anders wäre es bei: „User Dank gilt allen Mitwirkenden“

**Comment by McDiod** [comment]
Wat, das hört sich doch komisch an.

>an allen Mitwirkenden

**Comment by Synch2k** [comment]
"Unser Dank gilt allen Mitwirkenden" ist grammatikalisch korrekt.
"Danke auch an allen Mitwirkenden" ist falsch.

Entweder an und alle oder allen ohne an.

**Comment by chris579** [comment]
Ok hab’s falsch verstanden, dachte du meinst, man müsse das N ergänzen

**Comment by AdlerXiviD** [comment]
Fixed
