### ISSUE TITLE
Anleitung/Inhalt bei Spielstart

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/Adler_Base_18.Altis#3]
* Anleitung für die Basis bei Spielstart anzeigen
* Möglichkeit für Spieler, Anzeige bei Spielstart zu deaktivieren
* manuelles Öffnen der Anleitung auch über Tablet auf Tisch in der Nähe der Spawnposition möglich
* aufgebaut wie Field Manual
* möglichst simples Hinzufügen von neuen Einträgen / Editieren von bestehenden Einträgen als Missionsbauer

***
**Tablet auf Tisch**  
![anleitung](https://user-images.githubusercontent.com/16549968/33235291-a1005fb8-d235-11e7-8333-abe4c64f9efd.jpg)

**Anleitung mit "nicht mehr anzeigen" Checkbox**  
![anleitung](https://user-images.githubusercontent.com/16549968/33235292-a27a7c5c-d235-11e7-829d-03a7a1950dcd.png)

**Comment by McDiod** [comment]
Siehe #6

**Comment by AdlerXiviD** [comment]
Bin dafür! Sehr coole Idee!

**Comment by McDiod** [comment]
Pull Request bereit zum Mergen
