### ISSUE TITLE
Adler mit Adlerberet ausrüsten

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/Adler_Base_18.Altis#5]
Abfrage ob Spieler Adler ist:

```sqf
((squadParams player) select 0) select 1 == "Gruppe Adler"
```

**Comment by AdlerXiviD** [comment]
Wäre eine ganz nette Idee. Dafür müssten wir aber die Berets mit dem aktuellen Logo ausrüsten.

**Comment by chris579** [comment]
Man könnte das Logo des Adlerbaretts mit ner Hiddenselection versehen und dann dynamisch setzen. Dann müsste man Logo nicht im Model ändern. 
Pfad zur Textur kann man auch per `squadParams` abfragen.
