### ISSUE TITLE
Shooting Range Bug

### ISSUE THREAD

**Issue by Eras308** [gruppe-adler/Adler_Base_18.Altis#8]
![20171126193635_1](https://user-images.githubusercontent.com/31324871/33243501-bf8f8b68-d2e7-11e7-9e30-736ca87d96e7.jpg)

Ich habe auf der Schießbahn geschossen und habe mir die Treffer anzeigen lassen.
Dann habe ich die Entfernung verändert!

Dadurch haben sich die Treffer nach unten verschoben!

Zusätzlich gibt es immer einen Treffer auf der Bahnnummer, wenn man auf die Scheibe schießt!

**Comment by AdlerXiviD** [comment]
Die sind wahrscheinlich nicht nach unten verschoben sondern stehen noch auf der alte Position von vor dem Verschieben. Kann das sein?

**Comment by Eras308** [comment]
Kann sein!

**Comment by simmax100** [comment]
Mit der neuen Version, die die Tage kommt, nochmal versuchen.
Ich teste es aber auch nochmal.

**Comment by SlantX** [comment]
Der Bug existiert immer noch. Die Punkte bleiben in der Luft hängen, wenn die Scheibe nach hinten gesetzt wird. Man könnte es relativ einfach fixen, wenn man z.B. die Punkte resettet, bevor die Scheibe versetzt wird.
