### ISSUE TITLE
Vehicle Spawner über Mausrad

### ISSUE THREAD

**Issue by Eras308** [gruppe-adler/Adler_Base_18.Altis#9]
![20171126202021_1](https://user-images.githubusercontent.com/31324871/33243517-1f980062-d2e8-11e7-8130-cc850180e1be.jpg)

Ich konnte den Vihicle Spawner nicht aufrufen! 
Edit:
Würde mir eine Vihicle Spawner über das Mouseradmenü wünsche da alles andere in der Base auch darüber funktioniert.

**Comment by McDiod** [comment]
ACE-Interact

könnte man evtl. auf die Textur raufschreiben

**Comment by Eras308** [comment]
Ahh, geht übers ACE Menü! Wäre trotzdem übers Mausradmenü besser, da alles andere in der Base auch darüber funktioniert!
